'use strict';

export const CHANGE_WIDTH_AND_HEIGHT = 'CHANGE_WIDTH_AND_HEIGHT';
export const CHANGE_TAB = 'CHANGE_TAB';
export const TRACK_SCROLL_POSITION = 'TRACK_SCROLL_POSITION';


export const RECEIVE_TOPICS = 'RECEIVE_TOPICS';
export const RECEIVE_TOPIC_REPLIES = 'RECEIVE_TOPIC_REPLIES';
export const RECEIVE_USER_TOKEN = 'RECEIVE_USER_TOKEN';
