'use strict';

export const CHANGE_WIDTH_AND_HEIGHT = 'CHANGE_WIDTH_AND_HEIGHT';
export const TRACK_SCROLL_POSITION = 'TRACK_SCROLL_POSITION';


export const RECEIVE_TOPICS = 'RECEIVE_TOPICS';
export const RECEIVE_USERS = 'RECEIVE_USERS';
export const RECEIVE_NOTIFICATIONS = 'RECEIVE_NOTIFICATIONS';
export const RECEIVE_TOPIC_REPLIES = 'RECEIVE_TOPIC_REPLIES';
export const RECEIVE_MORE_TOPIC_REPLIES = 'RECEIVE_MORE_TOPIC_REPLIES';
