'use strict';

export default {

  REPLY_ITEM: 'REPLY_ITEM',
  LIKE_ITEM: 'LIKE_ITEM',
  FOLLOW_ITEM: 'FOLLOW_ITEM',

  USERNAME: 'USERNAME',
  PASSWORD: 'PASSWORD',

  NOTIFICATION_MENTION: 'Mention',
  NOTIFICATION_TOPIC_REPLY: 'TopicReply',
  NOTIFICATION_NODE_CHANGE: 'NodeChanged'
};