'use strict';

export const CHANGE_WIDTH_AND_HEIGHT = 'CHANGE_WIDTH_AND_HEIGHT';
export const CHANGE_TAB = 'CHANGE_TAB';


export const RECEIVE_TOPICS = 'RECEIVE_TOPICS';
export const REQUEST_TOPICS = 'REQUEST_TOPICS';


export const RECEIVE_REPLIES = 'RECEIVE_REPLIES';
export const RECEIVE_MORE_REPLIES = 'RECEIVE_MORE_REPLIES';
export const REQUEST_REPLIES = 'REQUEST_REPLIES';

