'use strict';

export const CHANGE_WIDTH_AND_HEIGHT = 'CHANGE_WIDTH_AND_HEIGHT';
export const CHANGE_TAB = 'CHANGE_TAB';


export const RECEIVE_TOPICS = 'RECEIVE_TOPICS';
export const REQUEST_TOPICS = 'REQUEST_TOPICS';


export const RECEIVE_REPLIES = 'RECEIVE_REPLIES';
export const RECEIVE_MORE_REPLIES = 'RECEIVE_MORE_REPLIES';
export const REQUEST_REPLIES = 'REQUEST_REPLIES';

export const RECEIVE_TOPIC_REPLIES = 'RECEIVE_TOPIC_REPLIES';
export const RECEIVE_MORE_TOPIC_REPLIES = 'RECEIVE_MORE_TOPIC_REPLIES';
export const REQUEST_TOPIC_REPLIES = 'REQUEST_TOPIC_REPLIES';

export const REQUEST_TOPIC_DETAIL = 'REQUEST_TOPIC_DETAIL';
export const RECEIVE_TOPIC_DETAIL = 'RECEIVE_TOPIC_DETAIL';

export const TRACK_SCROLL_POSITION = 'TRACK_SCROLL_POSITION';

export const REQUEST_USER_SESSION = 'REQUEST_USER_SESSION';
export const RECEIVE_USER_SESSION = 'RECEIVE_USER_SESSION';
