'use strict';

export default {
  TOPIC_TAB: 'TOPIC_TAB',
  NOTIFICATION_TAB: 'NOTIFICATION_TAB',
  ME_TAB: 'ME_TAB',

  REPLY_ITEM: 'REPLY_ITEM',
  LIKE_ITEM: 'LIKE_ITEM',
  FOLLOW_ITEM: 'FOLLOW_ITEM'
};